### ISSUE TITLE
Division Bug

### ISSUE THREAD

**Issue by dodaucy** [micropython/micropython#11809]
```py
MicroPython v1.20.0 on 2023-04-26; Raspberry Pi Pico W with RP2040
Type "help()" for more information.
>>> x = 92393249
>>> x + 1 == x
False
>>> x + 1 / 1 == x
True
>>> x + 1
92393250
>>> x + 1 / 1
9.239325e+07
```
```py
Python 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> x = 92393249
>>> x + 1 == x
False
>>> x + 1 / 1 == x
False
>>> x + 1
92393250
>>> x + 1 / 1
92393250.0
```

**Comment by robert-hh** [comment]
No bug. That's caused by the fact, that the Pico's float is single precision, but CPython works with double precision.  When you run:
` x + 1 / 1 == x`, the right hand x is converted to float for the comparison, and 
float(x)  returns 9.239325e+07, which is the same as `x + 1 / 1` on the Pico. Running the same test e.g. with a Teensy 4.x gets the same results as CPython, because the Teensy port uses double precision as well.

**Comment by dodaucy** [comment]
thanks :)
