### ISSUE TITLE
ord(b'\x80') throws a TypeError

### ISSUE THREAD

**Issue by dhylands** [micropython/micropython#1188]
In unix micropython:
```
2012 >./micropython 
Micro Python v1.4.1-78-g404b68d on 2015-04-18; linux version
>>> ord(b'\x80')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: ord() expected a character, but string of length 0 found
```

In python3:
```
2013 >python3
Python 3.4.0 (default, Apr 11 2014, 13:05:11) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> ord('\x80')
128
```

**Comment by dhylands** [comment]
Originally reported on the forum: http://forum.micropython.org/viewtopic.php?f=6&t=651&p=3724#p3717

**Comment by dpgeorge** [comment]
We had this issue before... `ord` is (implicitly) documented by CPython to work only for string (actually unicode) objects.  There's no mention of bytes/bytearray conversion.  Yet, as you found out, it does actually work for bytes (and bytearrays).  So we don't keep having this problem crop up I will fix it.

**Comment by pfalcon** [comment]
@dpgeorge : Please make it #if CPYTHON_COMPAT

**Comment by dpgeorge** [comment]
Actually, we do already support bytes to some extent, but it only works correctly for bytes chars < 0x80.  So the minimal fix is to just support bytes properly.  To have a CPYTHON_COMPAT option here would require a lot more code for the non-compatible version (since you need to then have an explicit check that it's a string object and issue an exception if it's not; currently this is done by mp_obj_str_get_data which raises an exception if the argument is not a str or bytes).

**Comment by dpgeorge** [comment]
Fixed.  @pfalcon if you still think it needs a CPYTHON_COMPAT option then please say so.  Maybe we need to ask upstream about fixing the docs regarding this?

**Comment by pfalcon** [comment]
Nope, looks good. And that's apparently a hidden py2 compat feature, probably not advertised on purpose ;-).
