### ISSUE TITLE
Pico: sdcard.py timeout waiting for v2 card

### ISSUE THREAD

**Issue by pollo1308** [micropython/micropython#12105]
give me this issue with kingston sd card 32 gb somebody help plis

**Comment by dpgeorge** [comment]
Please describe your hardware set up, the version of the code you are using, the code that you run, and the output from running.

**Comment by Flipje1955** [comment]
@pollo1308: had the same experience with 32GB cards of a variety of brands, using the official driver. Could not figure out what was wrong (am the first one to admit I am not in expert in the domain) but observed the issue only appeared with the 32GB type cards. 
I use 16GB cards since with the same sw and have no issues. Platform rp2040 of various brand boards. MP 1.19 / 1.20 incl intermediates (nightly builds).

**Comment by pollo1308** [comment]
my bad the vcc pin of the micro sd conect to vbus pin, not to 3.3v

**Comment by La89688** [comment]
Same experience. 32GB (Samsung Evo plus) didn't work either 5V and 3.3V. 16GB (Verbatim premium) works with 5V VSYS, but not working with 3V3(OUT) on Pi Pico.

**Comment by peterhinch** [comment]
Is the SPI bus shared with other hardware?

**Comment by La89688** [comment]
No, on this SPI is only SDcard module.

**Comment by RYoder97** [comment]
So, I understand that the issue may be the power connection and whether you use VBUS or 3V3 OUT, but what is recommended to be done to connect a Pico to Thonny AT THE SAME TIME? My PC probably isn't giving the Pico 5V via USB, so can I keep my Pico plugged into my PC while powering it from another source?

**Comment by b-blake** [comment]
Same error here with two different cards and two different card interfaces,
8GB Sandisk SD card & 32GB Samsung EVO Select SD Mini card.
5 volt VSYS power with onboard 3.3 volt regulator.
Both card format fine in a Windows 10 machine.

Adafruit CircuitPython 9.2.8 on 2025-05-28; Raspberry Pi Pico W with rp2040
Board ID:raspberry_pi_pico_w
UID:E6614103E719A637
MAC:28:CD:C1:00:6B:08

Bruce
