### ISSUE TITLE
Dynamically growing string size/allocsize problem

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#122]
Let's look at stm/main.c:file_obj_read():

```
    int n = mp_obj_get_int(arg);
    char *buf = m_new(char, n + 1);
    UINT n_out;
    f_read(&self->fp, buf, n, &n_out);
    buf[n_out] = 0;
    return mp_obj_new_str(qstr_from_str_take(buf, n + 1));
```

So, we're getting input data string of size n_out, but create qstr not of real size, but of alloc size. That "works" because we use \0 as string terminator so far.

But there's no place in qstr to store alloc size - now or in upcoming implementation. So, incorrect size will be passed to m_free(), which will lead to corruption with custom allocator.

Even without that, consider that we waste memory. Consider how read() w/o arg would be implemented - using growing vstr. If exponential growth policy is used (which is generally not ideal choice for embedded system), we can waste quite a lot memory wost case.

So, some general solution to this problem needs to be found. The "best" I can think of is to shrink buffer block for shorter strings using m_realloc(). As this would be called immediately after m_malloc(), these has best chance to avoid excessive fragmentation.

Any other ideas?

**Comment by dpgeorge** [comment]
This issue can be closed, because:
- (non interned) strings known their alloc and len (actually, alloc=len+1 so they only store len)
- strings created from vstrs will shrink the buffer to the exact length
- (almost) all calls to realloc and free include the previously-allocated size, so the GC doesn't need to store it (but this is a compile time option controlled by MICROPY_MALLOC_USES_ALLOCATED_SIZE)
