### ISSUE TITLE
Recasting current baremetal modules to "umachine"

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#1701]
@dpgeorge , @dhylands : I mentioned this couple of times in various related comments, but didn't get response, so here's explicit question:

I'd like to have more or less complete implementation of "machine" module for unix port. The primary motivation for that is testing, but we'll see where it goes. And good part of module would be implemented in Python using FFI, while some part in C, with requires separating module names. How we handle that so far is having builtin module with "u" prefix, and "module symlinks" for baremetal ports. So, I'm asking you how we should handle this for "machine" module.

**Comment by dpgeorge** [comment]
On unix, having a "umachine" module as the builtin C implementation, plus "machine.py" for extra stuff sounds good, just like we usually do it.

On baremetal, I would expect these ports to provide a full implementation of machine module straight away.  But I can see how there might be cases where it's not fully implemented, or you want to override it (perhaps to fix a bad implementation).  So going the "umachine" + symlink route sounds good here as well, since we use this pattern for pretty much all modules on baremetal.

**Comment by pfalcon** [comment]
@dpgeorge : Thanks

@danicampora : Any comments? Would you follow with this change? If so, should cc3200 port just be changed along the other ports?

**Comment by danicampora** [comment]
Yes, I'm OK with this change.

**Comment by pfalcon** [comment]
Implemented in 2eb844e0b4e649034115dd6ca77dcdecd92ef547
