### ISSUE TITLE
Return custom struct from c issue [ffi]

### ISSUE THREAD

**Issue by lapsule** [micropython/micropython#2192]
Here is a c demo lib:

```C
#include <stdio.h>

struct s {
        int a;
};

struct s getss(void)
{
        struct s ss;
        ss.a = 1;

        printf("return ss.\n");
        return ss;
}
```

involve in micropython:

```python
import uctypes,ffi
l = ffi.open('./liba.so')
gs = l.func('p', 'getss', 'v')
gs(None)
```

got Segmentation fault:

```sh
return ss.
[ 3442.782855] do_page_fault() #2: sending SIGSEGV to micropython for invalid write access to
[ 3442.782873] 00000000 (epc == 2b0ce720, ra == 2b0ce714)
```

**Comment by pfalcon** [comment]
Support for returning structure is a fragile and inconsistent topic handled differently in different ABIs. ffi module of course doesn't support that, and you will need to translate it to the underlying calling convention of ABI you use. For example, from the example above you somehow assume that instead of structure a pointer will be returned, thought I'm not sure how that can be explained.

You also incorrectly declare "gs" function on Python side. "v" is a return-only type and can't be used for arguments. Then, if a function doesn't accept argument, it's an error to pass one.
