### ISSUE TITLE
Board support request (EK-TM4C1294XL)

### ISSUE THREAD

**Issue by fkromer** [micropython/micropython#2215]
Do you plan to support the [TM4C1294 Connected LaunchPad ](http://www.ti.com/tool/ek-tm4c1294xl) (EK-TM4C1294XL)?

**Comment by pfalcon** [comment]
@fkromer: MicroPython is an open-source project, so the best way to get some board supported is to start preparing patches. The core maintainers have plans to well support few "official" boards, instead of spreading thin and support a little bit of everything. There's also a forum at http://forum.micropython.org with a section for 3rd-party boards support which is better suited for such discussions.
