### ISSUE TITLE
404 in upip causes subsequent usocket.getaddrinfo calls to give OSError: -2 (ESP8266 port)

### ISSUE THREAD

**Issue by askvictor** [micropython/micropython#2666]
If I try to install a package from upip, and it fails with a 404, then any subsequent calls to usocket.getaddrinfo() (for example, by another call to upip.install(), or by calling the function directly) will fail with OSError: -2. This appears to be a lwip error.

**Comment by pfalcon** [comment]
Thanks for the report. It would be helpful to provide more details, like explicit note that you tried that N times, and output dump. Because otherwise it looked like a typical "unstable connectivity" report (-2 from getaddrinfo() means no Internet connection).

This particular issue was fixed in upip 1.1.5:

~~~
>>> upip.install("foo123")
Installing to: lib/
Warning: pypi.python.org SSL certificate is not validated
Error: Package not found
>>> upip.install("micropython-copy")
Installing to: lib/
Installing micropython-copy 3.3.3-2 from https://pypi.python.org/packages/ce/2d/52606b9243ac65ce5ddae26f82d25a31b289b1d2580362528bf74065e5a4/micropython-copy-3.3.3-2.tar.gz
~~~
