### ISSUE TITLE
appveyor failing on builtin_help test

### ISSUE THREAD

**Issue by dpgeorge** [micropython/micropython#2806]
Since 1864f90e9a2c0cc12e91c88ddd491b809c5317e5 it seems that appveyol is failing on the builtin_help test.  I'd say it should be skipped automatically, because there is no built-in help function on the windows build, but something is not working.

@stinos can you please look into this when you have some time, thanks.

**Comment by stinos** [comment]
The standard unix build has the same problem, the output is `######## FAIL` so seems to be some problem with handling special tests?

**Comment by stinos** [comment]
Two problems here:
- there's no support fro skipping the special tests, easily fixed by adding a `if output_mupy == b'SKIP\n': return output_mupy` at line 146, I'll add a PR for that
- treating tests as special relies directly on the arguments passed in by the user so calling `./run-tests ./basics/builtin_help.py` is not the same as calling `./run-tests basics/builtin_help.py`
