### ISSUE TITLE
ffconf.h additional define

### ISSUE THREAD

**Issue by microwavesafe** [micropython/micropython#2826]
@dpgeorge 
Would you accept a pull request for an additional define around _FS_NORTC in lib/oofatfs/ffconf.h ? My port doesn't have an RTC so this would be useful to set to 1. I would imagine there are quite a few applications that have no need for the actual time. Or would you prefer I use the FFCONF_H mechanism to include my own header?

I would do something like this.
```
#ifdef MICROPY_FATFS_NORTC
#define _FS_NORTC   (MICROPY_FATFS_NORTC)
#else
#define _FS_NORTC   0
#endif
```

**Comment by dpgeorge** [comment]
> Would you accept a pull request for an additional define around _FS_NORTC in lib/oofatfs/ffconf.h ?

Yes.  Anything in ffconf.h can have a corresponding MICROPY_FATFS_xxx config option.  It is possible to have a port-specific file, but I think it's better to use a common one for all ports like it is now so that if there are new options in new versions of fatfs then each port automatically gets the defaults for these new options.
