### ISSUE TITLE
mDNS support for ESP8266?

### ISSUE THREAD

**Issue by janfredslund** [micropython/micropython#2875]
It doesn't seem to be possible to assign a hostname to a device on the local network, so you can connect to it via webREPL instead of setting a static IP or configure the router's DHCP. On the Arduino core for ESP8266 you can use the mDNS library.

**Comment by pfalcon** [comment]
There's no such support currently. You're welcome to develop it if you need, that's the whole idea of MicroPython - to allow people to develop and use variety of tools and applications. You may find alike-thinking people on the forum, https://forum.micropython.org/, and cooperate with them.
Let me close this otherwise, this is primarily a bugtracker, and with almost 400 tickets open, it gets really hard and time-consuming to manage real bug reports in there.
