### ISSUE TITLE
Proper way to create a Cpython object that has a property?

### ISSUE THREAD

**Issue by MrSurly** [micropython/micropython#3027]
How can I add a property (i.e. `mp_type_property`) as part of an objects locals dict?

**Comment by dpgeorge** [comment]
The recommended way to make a class with attributes is to implement the `.attr` C function in the class's `mp_obj_type_t` struct; see py/objcomplex.c for an example (it has real and imag attributes).  Not all ports will have properties so that's why it's recommended to do it this way.

These types of developer questions are best posted at https://forum.micropython.org

**Comment by MrSurly** [comment]
> These types of developer questions are best posted at https://forum.micropython.org

How on earth have I not seen this before?  Sorry.
