### ISSUE TITLE
Will micropython support GSM/GRPS module in the future?

### ISSUE THREAD

**Issue by HB4daemmon** [micropython/micropython#3133]
Dear all,

Will micropython support GSM/GRPS module in the future?
Now micropython supports wlan(CC3K) and ethernet(WIZNET5K), however these two ways can't let pyboard to spread everywhere.
Wlan and ethernet all have limitations as information dissemination mode, because we can't get them everywhere.
I would really appreciate it if micropython will support GSM/GRPS module in the future.
Thanks.

**Comment by dpgeorge** [comment]
It's possible to make an add-on GSM/GPRS module work with the pyboard, like the Adafruit FONA board.  See https://forum.micropython.org/viewtopic.php?f=5&t=507 for some initial work on that which you might be able to build upon.

Otherwise, there are no plans for the immediate future to support a specific cellular module.

Since github here is mainly for tracking bugs and new features being developed, I'll close this issue.
