### ISSUE TITLE
Example implementing a NIC

### ISSUE THREAD

**Issue by diogoviannaaraujo** [micropython/micropython#3309]
Hi,

Ive been experimenting with micropython. Ive trying to interface with a sim808 module. Ive understood most part of ur networking stack, I've read the issues about networking modules, socket and etc.

But I can't find any example on how to write a NIC in python. I can see some drivers on root folder with some network module named files. But that does not seems to implement what I need. Is it inside each port? Where do you guys implement each Network.xxx?

Im willing to spend some good time contributing to this, any help appreciated.

Edit1: As far as I could understand most of the NIC classes are per port (which I found weird) and most of them are wrote in C. Since serial communication is implemented by upython, is it possible to add another one with plain python? Will I be needed to recompile upython? thanks in advance

**Comment by dpgeorge** [comment]
> But I can't find any example on how to write a NIC in python.

There are no such examples.  All the NIC code so far is written in C, for performance reasons, and also because NICs can be very complex and often have existing code written in C to support them.

> As far as I could understand most of the NIC classes are per port

Yes, because in most cases the NIC that is available is specific to the port.  Eg esp8266 has a custom device, and cc3200 has a cc3100 deeply integrated into it.  And then the socket module needs to integrate tightly to the NIC so that's also done in C.

You can still implement your own NIC and socket class in pure Python: you'd write some code to set up and configure the external network device, then make a custom socket module (in Python) that talks to the NIC.  I have done done it this way before for a few different network devices (although such code is not published anywhere).

It is actually easier to write your NIC driver in Python to start with, then gradually convert it to C for performance.  The C code can also be generic enough to run on all ports.

Anyway, such a discussion is better suited to the forum: https://forum.micropython.org
