### ISSUE TITLE
openwrt/lede build error

### ISSUE THREAD

**Issue by apatrushev** [micropython/micropython#3325]
Latest `micropython` failed to build for `openwrt`/`lede`. The reason is strict check here: https://github.com/micropython/micropython/blob/72732fea1a041b94448d98ad4fd53545caa758ab/py/persistentcode.c#L377

Not all openwrt/lede target platforms are `__arm__`. I suggest to remove `__arm__` check from ifdef.

**Comment by pfalcon** [comment]
@dpgeorge : Why do we have mpy-cross specific code in the core in the first place?

**Comment by dpgeorge** [comment]
@apatrushev I assume the build is failing when building the "mpy-cross" component, right?

> Why do we have mpy-cross specific code in the core in the first place?

That code is supposed to be "generic", useful for any port to save bytecode, and was there before mpy-cross existed; see d8c834c95d506db979ec871417de90b7951edc30

As the comment says, this code needs to be abstracted away properly by ports providing "save to file" functionality.  But to fix it temporarily this code could be wrapped by a new config variable such as MICROPY_PERSISTENT_CODE_SAVE_POSIX (since it relies on open, write and close functions), or an easier thing is to just do what's done by #3326.

**Comment by dpgeorge** [comment]
Fixed by PR linked above.
