### ISSUE TITLE
Recursive quicksort causes stack overflow

### ISSUE THREAD

**Issue by deepgully** [micropython/micropython#338]
I just have 4K runtime stack, sort a list with 50 items will hang the system
```python
li = list(range(50))
li.sort()    # stack overflow!
```
I have change quicksort to non-recursive version, it supports list > 100000 now.

**Comment by dpgeorge** [comment]
Minimal modification made to list.sort so that it uses at most O(log(N)) stack space.  It's a much smaller (read micro) change than proposed by @deepgully.  In particular it doesn't need to dynamically allocate stack space (it still uses the C stack) and so plays nicer with the memory allocator.

So this issue is fixed.  One thing remaining -- which is a separate issue -- is that our list.sort is not stable, whereas the Python specs say it should be.  We should probably care about this since it could create subtle bugs in code ported from CPython to uPy or vice-versa.  See eg http://h2database.googlecode.com/svn/trunk/h2/src/tools/org/h2/dev/sort/InPlaceStableQuicksort.java for an in-place stable quicksort; or maybe we use a different sorting algorithm altogether.
