### ISSUE TITLE
stm32 port uos.listdir() displaying \x00's

### ISSUE THREAD

**Issue by Lisa999** [micropython/micropython#3430]
Create empty dir using usb share, goto it:

&gt;>> uos.chdir('test')
&gt;>> uos.listdir()
['\x00\x00\x00\x00\x00\x00\x00\x00.\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00.\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00.\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00.\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00.\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00.\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00.\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00.\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00.\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00.\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00.\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00.\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00.\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00.\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00.\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00.\x00\x00\x00'] 

huh? Same problem with uos.ilistdir()

IF dir is created with uos.mkdir('test2'), it works:

&gt;>> uos.mkdir('test2')
&gt;>> uos.chdir('test2')
&gt;>> uos.listdir()
[]

**Comment by robert-hh** [comment]
The interaction between file operation cause by a host through the file share and the local file operations is a ongoing source for trouble. Do not mix these. Either use if though the file share only, and never forget to properly eject the device, or only locally. For myself, I have disabled the file share, and since then file operations on the Pyboard are reliable.
