### ISSUE TITLE
print(a=2) does not throw invalid keyword error

### ISSUE THREAD

**Issue by goatchurchprime** [micropython/micropython#3467]
In fact there is no error at all.  Unrecognized keywords are ignored.  

On normal python the response is:

```
>>> print(a=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'a' is an invalid keyword argument for this function
>>> 
```

I found this one when I was teaching a non-programmer the difference between conditional == and assignment = and had not even got to the bit about functions and keyword arguments.

**Comment by dpgeorge** [comment]
Thanks for the report.

This is a general limitation of some of the built-in functions and methods in MicroPython, that not all keyword args are checked in order to keep the code size minimal.

But in this particular case, rewriting the print function to check all keyword args (by using a helper function) actually reduced code size.  See the fix in 58f00d7c0e116e17ab141ae18275edea14b88431 which should fix the issue reported here.
