### ISSUE TITLE
RFC: Configurability and parametrization

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#35]
When developing full-fledged language implementation for constrained environment, there're number of choices, compromises and optimizations to make. For different environments, different choices make sense. So, it's import to support (compile-time) configuration, and in this ticket I'd like to discuss:
1. Amount of configurability we want to allow.
2. Specific guidelines on how overall configuration and individual parameters are handled.

Let's start with pronouncing the of adding too much configurability - it may be hard to maintain the project and test individual optimizations, and even harder to test various combinations of them. With that in mind, I still think that having localized optimizations (i.e. not interdependent) and good testsuite should make advanced configurability feasible. As an example, I imagine configurability down to the level of individual methods of builtin types (so for example, if particular application never uses str.join() method, MicroPython can be built without it, which will allow it to run in a more flash-constrained environment, or fit more useful functionality in flash instead).

Regarding configuration params, currently it is handled by per-port (essentially, per build variant) mpconfig.h file, like:

```
#define MICROPY_ENABLE_FLOAT        (1)
#define MICROPY_EMIT_CPYTHON        (0)
#define MICROPY_EMIT_X64            (1)
#define MICROPY_EMIT_THUMB          (0)
#define MICROPY_EMIT_INLINE_THUMB   (0)
```

That seems good approach, because passing gazillion of potential option via compiler command line doesn't scale. To not require to specify each and every option in mpconfig.h, it makes sense to have py/default_config.h which will use #ifdef to set sensible defaults for options. Otherwise, mpconfig sets convention of having "MICROPY_" prefix for config option, and used #if (not #ifdef) for testing option in source code.

I myself already introduced "USE_READLINE" config param which doesn't follow the convention above, but it's kinda special as it affects only "unix" port (not language core) and related to licensing (readline casts resulting binary to GPL).

Thoughts?

**Comment by dpgeorge** [comment]
This can be closed because configuration has been well defined for some time.  A short summary:
- py/mpconfig.h provides the master list of configuration options (the ones controlling all code in py/ and most of the code in extmod/).  It provides sensible defaults for when config options are not specified by mpconfigport.h.  When creating an mpconfigport.h file it's recommended to only define those config options which are different from the default.
- Options that control entities in the Python API are named `MICROPY_PY_xxx`.  There are some special cases like `MICROPY_PY_ASYNC_AWAIT`, but for the most case they are of the form `MICROPY_PY_<module>` to enable a module, `MICROPY_PY_<module>_<class>` to enable a specific class/feature within a module, and `MICROPY_PY_BUILTINS_<name>` to enable a specific builtin/feature.
- Most other options start with `MICROPY_` are should be descriptive enough.
