### ISSUE TITLE
mphal.h - #ifndef used to check for existence of a function?

### ISSUE THREAD

**Issue by adritium** [micropython/micropython#3603]
It appears that `#ifndef` is used to check for existence of a function; [that is not allowed in C](https://stackoverflow.com/questions/6234755/does-ifdef-or-other-preprocessor-directives-work-for-function-declarations-t).
Only existence of MACROS can be checked with `#ifndef`.

```
#ifndef mp_hal_stdout_tx_str
void mp_hal_stdout_tx_str(const char *str);
#endif
```

**Suggestion**: 
If `mp_hal_stdout_tx_str` - and all the other arguments of `#ifndef` in this file - are meant to be macros, I suggest the entries in this file be changed to indicate they are macros i.e. by CAPITALZING them.

```
#ifndef MP_HAL_STDOUT_TX_STR
    void MP_HAL_STDOUT_TX_STR(const char *str);
#endif
```

I get the logic: if the macro is not defined, then it's defined as a regular function so declare the function here and it will be defined somewhere else.
But it just seems  . . . non-standard to mix the **existence** of a macro with the **declaration** of a function.

Why not follow the same pattern as in `mpconfig.h`? 
If macro doesn't **exist**, create its **definition** here:

```
#ifndef MP_HAL_STDOUT_TX_STR
    #define MP_HAL_STDOUT_TX_STR(a) /* insert code here */
#endif

```

**Comment by dpgeorge** [comment]
> If mp_hal_stdout_tx_str - and all the other arguments of #ifndef in this file - are meant to be macros,

They are either functions or macros, depending on how the port wants to configure it.  The idea is that you either 1) implement the function with the same signature; 2) define the macro of the same name to provide whatever implementation you need (eg some inline code).  See eg https://github.com/micropython/micropython/blob/master/ports/cc3200/hal/cc3200_hal.h#L67-L68 for an example of the latter use.

> I suggest the entries in this file be changed to indicate they are macros i.e. by CAPITALZING them.

They are for most ports functions, so that's why they are lower case.

> Why not follow the same pattern as in mpconfig.h?
> If macro doesn't exist, create its definition here:

But the definition is not known in mphal.h.  It's only known by a port.

**Comment by dpgeorge** [comment]
I assume this point was clarified.
