### ISSUE TITLE
Freeing memory allocated in c module

### ISSUE THREAD

**Issue by mzakharo** [micropython/micropython#3606]
Is there a process by which memory, allocated by a c module using malloc is freed when object is garbage collected by the interpreter? Is there a hook to __Del__ method or something similar?

**Comment by dpgeorge** [comment]
Memory that is malloc'd from C can be explicitly free'd, or left for the GC to reclaim.  You can add a finaliser by allocating your memory block with `m_malloc_with_finaliser` and then implementing the `__del__` method in the object type.  See eg `extmod/vfs_fat_file.c` for an implementation/use of this feature.

**Comment by mzakharo** [comment]
Thank you very much!

**Comment by gengshenghong** [comment]
@dpgeorge Can you please confirm that if I implement a C module for uPy, I cannot (should not) use "malloc/free" in it, if the memory may be free'd by GC automatically? I guess it will cause random crash if it will be free'd?

I did a test, write a simple C function call for uPy, I'll "malloc" some memory in it, test with below code:
```
import gc
import ttt

gc.collect()
gc.mem_free()	# value1
gc.collect()
ttt.malloc(10000)
gc.mem_free() # value2
```

vlaue2 will be same with value1 (not less than 10K). If I use "m_malloc" in "ttt.malloc", value1 - value2 will be 10K. If "maloc/free" cannot be used, can I use "m_malloc" safely? will it also be free'd by GC automatically?

I am testing with esp32, I test this because uPy runs as a task  of freeRTOS on esp32, how about if I want to run other tasks (un-managed by uPy) together with uPy which will have its own memory management?

Background: I submitted #4372 , in that issue, http server is affected by Python threads, after some analysis, I guess it is because of GIL performance issue, and if I start a http server using pure C with rtos task, it will not be affected. So, I guess it is a good solution for that issue, but before that, I want to confirm if memory management will be issues when more code are added as logic of the http will requires some dynamic memory in C code.

Looking forward to your suggestions.

Thanks,
Shenghong
