### ISSUE TITLE
Python for the 8bit AVR mocrocontroller

### ISSUE THREAD

**Issue by slavaza** [micropython/micropython#3699]
I has compiled Micropython in minimal configuration, for the AVR8 microcontrollers. Just for the sake of curiosity. The footprint is shown below.

AVR8 uPython VM with Compiler
 text       data      bss     dec         hex        filename
 96580   11430  2288   110298   1aeda    build/firmware.elf

Maybe it will be interesting to someone?

**Comment by 3bb** [comment]
Yes :+1:

**Comment by slavaza** [comment]
@rolandvs Good. Unfortunately I can not demonstrate a workable port to AVR8. This would require significant costs as for me. You can install and try compile by yourself by installing the `avr8-dummy` port from my repository.

**Comment by aofek** [comment]
very good idea
it is about time to use a single language on embedded systems
8b ,16b , 32b , 64b they all should use one language, preferably python

learn st8, st32,esp32,msp430, Arm Mbed, Arduino, Adafruit and many more....  one spend more time on learning language than on applying algorithms....

Thanks Slavaza

**Comment by jonnor** [comment]
For reference, the mentioned repository appears to be https://github.com/slavaza/micropython-avr8

**Comment by mattytrentini** [comment]
It's good to see a port of MicroPython to AVR, even if it's fairly rudimentary. However, the core team is focussed on 32-bit microcontrollers and it seems low-value to target 8-bit devices, especially since, for that class of device, only a small percentage has sufficient flash. 

We will definitely help answer questions and provide guidance about the porting effort. But I think it unlikely that such a port will be accepted upstream unless someone will show clear willingness to own and, especially, support such a port. 

So, I think it reasonable that we close this ticket, at least until such a person steps forward.
