### ISSUE TITLE
mp_obj_new_module should not automatically add to MP_STATE_VM(mp_loaded_modules_dict)

### ISSUE THREAD

**Issue by adritium** [micropython/micropython#3724]
Many Python objects have `.c` `init` functions that set the `.base` and prepare the newly allocated object for operations.

`mp_obj_new_module(qstr module_name)` does that but it also always adds it to `mp_loaded_modules_dict`.

What if I want to have `module1.module2.module3....` and I use this function to initialize each of these modules? They would all be added to the top-level dict and the user could write `import module2` instead of `import module1.module2`.

Or am I not using modules correctly?

**Comment by dpgeorge** [comment]
> mp_obj_new_module(qstr module_name) does that but it also always adds it to mp_loaded_modules_dict.

Yes, this is necessary so that if code imports a module a second time then it doesn't re-import it, but rather just gets a reference to the first instance that was already imported.

> What if I want to have module1.module2.module3....

That means you are implementing packages using C code.  That's not currently supported by the import system.  Only packages implemented as Python scripts are implemented.
