### ISSUE TITLE
DHT has no type hints

### ISSUE THREAD

**Issue by alleycat58uk** [micropython/micropython#3899]
The DHT driver has no type hints and, in my IDE, it flags an unresolved reference when I try to import.  I'd be happy to submit a pull requerst, do I make the changes directly to drivers/dht/dht.py?

Type hints were mentioned in May 2015 in #1281

**Comment by dpgeorge** [comment]
None of the Python libraries/drivers here make use of type hints.  I guess that's more or less a conscious decision because adding them would increase the size of the scripts (although not compiled code) and create a dependency to the `typing` module which is not implemented.

> Type hints were mentioned in May 2015 in #1281

Yes, but that's about the viper emitter which implements a low-level, native mini language within MicroPython, and needs type hints to work.

**Comment by dpgeorge** [comment]
There are no current plans to add type hints, so closing.
