### ISSUE TITLE
Micropython ESP32 - DHT22 measure fails when there are too many threads

### ISSUE THREAD

**Issue by mistermoper** [micropython/micropython#4037]
Hi. I have a ESP32 devkit v1 board with micropython installed and I have problems with dht measuring when I am doing more than one thread.

The main purpose with DHT22 which I want implement is this:
- Publish temperature and humidity to MQTT each 30 seconds..
- Publish temperature and humidity to MQTT when a specific MQTT event is received.

I had this working using a thread for each objective but when I add one thread more DHT measure stop working, it throws ETIMEDOUT exception.

What is the problem and how I can fix it?
Thanks!

**Comment by dpgeorge** [comment]
Because this is more of a "how to" questions, it is much better to ask it on the forum: https://forum.micropython.org .  You would need to post your code to make it possible to see the issue.

In general with multithreaded programming you need to be careful that two threads don't access the same resources (eg a DHT sensor) at the same time.
