### ISSUE TITLE
bytearray.fromhex() returns attribute error

### ISSUE THREAD

**Issue by rlnktt** [micropython/micropython#4052]
print(bytearray.fromhex("3E3E3E"))

When I tried this on repl, it produced the following error

Attribute Error: type object 'bytearray' has no attribute 'fromhex'

**Comment by robert-hh** [comment]
Indeed. That's because Micropython is micro. Use ubinascii.unhexlify instead.

**Comment by rlnktt** [comment]
@robert-hh By the way, do you mean 'binascii' instead of 'ubinascii'?

**Comment by robert-hh** [comment]
No. In Micropython, the module is called ubinascii, with binascii as alias.

**Comment by rlnktt** [comment]
Thanks @robert-hh  for the reference!! It worked like a charm.

**Comment by Xarbenence** [comment]
I know it's been awhile since this thread has seen any activity, but I figured I would ask. I am attempting to do what rlnktt was seeking to do when he started this thread, and I started in the same manner: attempting to use byte.fromhex(...).

I then found this thread and, after reading robert-hh's, response attempted to use ubinascii.unhexlify. Unfortunately, I received the error "no module named ubinascii," and after that I tried regular binascii, but to the same results. Does anyone know why I might be getting this error? For reference, I am using micropython on a micro:bit.

**Comment by dpgeorge** [comment]
> For reference, I am using micropython on a micro:bit.

The microbit (running MicroPython) doesn't have the `binascii` module enabled.

**Comment by Xarbenence** [comment]
> > For reference, I am using micropython on a micro:bit.
> 
> The microbit (running MicroPython) doesn't have the `binascii` module enabled.

Thank you for the fyi. Is there a way I can manually turn a bytestring to hexadecimal? I have found .hex() and hexlify methods online, but since those methods are unavailable on the micro:bit I'm trying to find a workaround.

**Comment by dlech** [comment]
```python
data = b"\x01\x02\x03\x04"
":".join("{:02x}".format(x) for x in data)
```

**Comment by Xarbenence** [comment]
> ```python
> 
> data = b"\x01\x02\x03\x04"
> 
> ":".join("{:02x}".format(x) for x in data)
> 
> ```

Wow. Thank you very much! That one line of code was honestly fundamental to making a project of mine work.

**Comment by Xarbenence** [comment]
> > For reference, I am using micropython on a micro:bit.
> 
> 
> 
> The microbit (running MicroPython) doesn't have the `binascii` module enabled.

Thank you, Mr. George! Also, during some research I learned that you are the creator of MicroPython, and I just wanted to say thank you, not only for your brilliant idea to put Python on microcontrollers, but for also being willing to reply to people
who are new to using this tool. It's a bit amazing to me that you'd take the time to do that, so thanks again.

**Comment by dpgeorge** [comment]
Actually, you should thank @dlech  :smile:
