### ISSUE TITLE
[help] It's not clear how C modules should deal with memory allocation 

### ISSUE THREAD

**Issue by Ecco** [micropython/micropython#4306]
I'm writing a module in C and I'd like to tap into MicroPython's heap. My C code doesn't output Python objects but needs some (dynamic) memory nonetheless to do its job. The problem is that the GC will most likely collect my buffers while I still need them.

Question: what's the proper way for a module to play well with the GC and mark some global variables as GC roots so that it doesn't wipe them?

**Comment by dhylands** [comment]
You need to ensure that you can get to your block by following pointers starting from a "root" pointer. Then the GC won't collect it.

One way to do this is to add pointers into the MICROPY_PORT_ROOT_POINTERS macro defined in mpconfigport.h The STM32 one is here for example:
https://github.com/micropython/micropython/blob/master/ports/stm32/mpconfigport.h#L265

You access members of this structure using the MP_STATE_PORT macro, like this:
https://github.com/micropython/micropython/blob/51482ba92568a9793fea34213ed74be850920a5a/ports/stm32/timer.c#L801

Fundamentally, each port provides a function called gc_collect. This function must call gc_collect_start which takes care of the root pointers described above:
https://github.com/micropython/micropython/blob/51482ba92568a9793fea34213ed74be850920a5a/py/gc.c#L333

Then the port can add additional root pointer areas.

**Comment by Ecco** [comment]
Thanks for your answers @dhylands ! Great explantions, thank you! I still have a few questions though:
* As an alternative, is it possible to directly add an extra call to `gc_collect_root` in the port's `gc_collect`? With a pointer to the new area of course.
* Is it possible to add some gc roots from within the module's code? Modifying `MICROPY_PORT_ROOT_POINTERS` is done at the port level, and so is `gc_collect`. This adds some unpleasant coupling between a port and its modules… It seems like it would be somewhat redudant with `MICROPY_PORT_BUILTIN_MODULES`.
* Why is there a `gc_free` function? I thought the point of GC was precisely not to manually free memory.

**Comment by dhylands** [comment]
> Thanks for your answers @dhylands ! Great explantions, thank you! I still have a few questions though:
> 
>     * As an alternative, is it possible to directly add an extra call to `gc_collect_root` in the port's `gc_collect`? With a pointer to the new area of course.

Yes - that would work.

>     * Is it possible to add some gc roots from within the module's code? Modifying `MICROPY_PORT_ROOT_POINTERS` is done at the port level, and so is `gc_collect`. This adds some unpleasant coupling between a port and its modules… It seems like it would be somewhat redudant with `MICROPY_PORT_BUILTIN_MODULES`.

Unfortunately, there isn't currently a way that has a finer granularity than the port level. PR #4195 seems like a good place to bring this up.

>     * Why is there a `gc_free` function? I thought the point of GC was precisely not to manually free memory.

It allows the C code to explicitly free memory if it knows it doesn't need it any more. Freeing early helps reduce heap fragmentation. Many times, though the C code can't know and shouldn't call gc_free. One place it could be used while constructing an object and something fails. You could free the object since python has never seen it and the C code knows there aren't any pointers to it.

It's also useful when integrating other C libraries which expect to call malloc/free.

**Comment by pfalcon** [comment]
Polluting root pointer set with more root pointers is generally discouraged. If you need to do that, you as well can likely allocate it statically. Otherwise, you just should store pointer to any buffer in a Python object, which is returned from some function in your module. As long as user keeps reference to that object, allocated memory will stay. When all references are gone - memory will be freed on the next GC, just as user expects.

**Comment by dpgeorge** [comment]
@Ecco were your questions fully answered, can this issue be closed?

**Comment by Ecco** [comment]
Yes, they were, thanks!
