### ISSUE TITLE
Mixin failing on kwargs

### ISSUE THREAD

**Issue by Sult** [micropython/micropython#4937]
I am pretty complexed
I am working with some class inheritance, and for some reason my __init__ keeps erroring out with the message:
TypeError: function doesn't take keyword arguments

To try it out, i set all init methods to just be *args ,**kwargs, but i am still getting the same error
Below is a snippet of my code
https://gist.github.com/Sult/0108386e1d530a509ce8bcdc4f147af5

When i use 1 args:
`sens = Waterpump(0)`

function takes one positional arguments but 2 where given

if i use 1 named argument
function doesnt take keyword arguments

only when i use no input at all, it passes.

Can someone please explain what i am missing here?

`

**Comment by jimmo** [comment]
The issue here is that `SleepMixin` thinks its super is `object` (whose `__init__` does not take any args or kwargs). The MRO is not correct, unfortunately this is something where MicroPython differs from CPython. See https://docs.micropython.org/en/latest/genrst/core_language.html#method-resolution-order-mro-is-not-compliant-with-cpython

To see what is going on, here's a minimal test case based on your classes:

```python
class AnalogSensor(object):
    def __init__(self):
        print('analogsensor __init__')

class SleepMixin(object):
    def __init__(self):
        print('sleepmixin __init__')
        super(SleepMixin, self).__init__()  # Calls object.__init__ on MicroPython, but AnalogSensor.__init__ on CPython

class Waterpump(SleepMixin, AnalogSensor):
    def __init__(self):
        print('waterpump __init__')
        super().__init__()

w = Waterpump()
```

```
$ ~/src/github.com/micropython/micropython/ports/unix/micropython jobs.py 
waterpump __init__
sleepmixin __init__

$ python3 jobs.py 
waterpump __init__
sleepmixin __init__
analogsensor __init__
```

**Comment by Sult** [comment]
Thanks a lot! i thought i was going mental
