### ISSUE TITLE
Ghost interrupts on GPIO39/Sensor_VN

### ISSUE THREAD

**Issue by gmos** [micropython/micropython#5425]
I have 4 identical input circuits on ESP32-WROVER GPIO's 39, 34, 35, 27.  All 4 configured to do a call back on rising and falling signal.  Worked flawlesly for months.
Yesterday I have upgraded the SDK and Micropython to the latest available V3 version (6ccb4cf5b7d1fdddb8c2492f9cbc926abaf230df).
Suddenly I getting regularly spurious interrupts on GPIO 39, perhaps once every second.  The other 3 GPIO's are still ok.
On my scope I see a very short pulses when the interrupts happen. Pin is pulled high with 3k3, and the voltage drops with about 1v a very short while.

Problem reproduces on multiple boards.

After digging into the https://www.espressif.com/sites/default/files/documentation/esp32_hardware_design_guidelines_en.pdf section 2.1.6 on page 7 the hardware issue is probably explained there.  It has to do with ADC or Hall activity.  They recommend to work around in software.
I'm not using one of the ADC's nor the Hall.

What causes the change in behaviour since the upgrade of Micropython and the SDK?
Is this a bug that will be fixed?

**Comment by dpgeorge** [comment]
> What causes the change in behaviour since the upgrade of Micropython and the SDK?

It depends which version you started with, which version was working OK.  But most likely it's due to an update of the IDF, eg due to change in how the WiFi power saving feature works.

> I'm not using one of the ADC's nor the Hall.

SARADC2 is used by the WiFi and also affects GPIO 39 (SENSOR_VN) according to the hardware design guidelines.

> Is this a bug that will be fixed?

The problem sounds like a limitation of the hardware and not something that's easily addressed on the MicroPython side.

**Comment by gmos** [comment]
Yes. Also suspected an IDF change.  Well, no interrupts on this input.  The pulse is so short that I still can use it as a level input.
Thanx.
