### ISSUE TITLE
Multithreading support

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#595]
This is one of the questions which always has been "in the air", but which I was shy to raise, as it seemed so far-fetched and could only distract people from real targets. Well, given positive response to similar issue, #583, and the fact that people start talking about it (e.g. http://forum.micropython.org/viewtopic.php?f=2&t=15#p238), let's get this out of head(s) into open.

So, is there interest to support multithreading in MicroPython, that it is, ability to run independent Python code in two+ preemptively scheduled threads? If yes, it's not going to be easy to implement:
1. First of all, access to shared resources. Let's dismiss GIL right away - it's not multithreading, but then GC heap is very contentious resource to share.
2. To not bother with sharing other stuff, best to have complete snapshot of execution environment (namespaces, etc.) => memory usage.
3. Either way, interpreter code need to be able with specific execution env (per thread), so it will need to be kept in a structure and accessed as such. Execution env ptr needs to be stored somewhere too (thread local data if it exists and fast is good, also can pass explicit ptr to each and every API func ;-) ).
4. To add to point 2, uPy stack usage is now probably ~awful, so that would need to be optimized too (well, needed anyway of course).

**Comment by EcmaXp** [comment]
https://github.com/EcmaXp/mpoc/tree/91c5611782eb0a2e1738bb381f523debdebd00d1/mpoc-rom/
https://github.com/EcmaXp/micropython

afk

**Comment by pfalcon** [comment]
@EcmaXp : That looks interesting, but unfortunately, there's no documentation, no design notes, no requirements. One the reasons I implemented stackless support in uPy is to make it possible to implement dynamic, Lua-style coroutines. Greenlets are very close to them, but I'm not sure about API they provide. Lua coroutines are truly minimal (good match for *Micro*Python) and cooperatively scheduled. Let me know if you're interested in implementing them (that would mean taking your code and simplify it a lot, or possibly, rewrite).

**Comment by EcmaXp** [comment]
@pfalcon : Yes. I should rewrite my code (+ some test, document, design note) if decided implementing greenlet in micropython. Currently i used them for limiting execute on game (on Minecraft's OpenComputers), when i finish my work (~2015-12-01 ?), i will make new brench.

**Comment by EcmaXp** [comment]
Still no documentation, no design notes, no requirements. but i almost finish to support thread in micropython.

Problem is comparison are really big.
https://github.com/micropython/micropython/compare/master...EcmaXp:opencom

**Comment by dpgeorge** [comment]
@EcmaXp a lot of the code has changed in the past month (most notably adding MP_OBJ_TO_PTR and MP_OBJ_FROM_PTR in lots of places) so that's going to make it hard to get a clean diff of your changes.

But it's very interesting what you have done.  Can you explain in a bit of detail the scheme you are using, where state is stored for each "thread", how much RAM it uses, how and when it switches to other threads, and how you protect against concurrent use of the heap/gc?

**Comment by EcmaXp** [comment]
C (or Java in my case) can spawn **native thread**
Only one thread can access the `mp_state_ctx` after `mp_state_load`. (and release by `mp_state_store`)
`MICROPY_MULTI_STATE_CONTEXT` mecro makes multi `mp_state_ctx` and `mp_nlr_top` (`MP_STATE_VM(nlr_top)` will remove when multi state enable).
It require enable `MICROPY_NLR_SETJMP` because asm code can't access TLS value (i don't know about any asm code).
`THREAD` mecro is `__thread`
`MP_THREAD` is (`THREAD` if `MICROPY_MULTI_STATE_CONTEXT` else '' (nothing))
Maybe it require custom module like `sys` (it have `argv`, `path`, `modules`). `builtins` (because i need override some builtin value)

And python code can spawn **green thread**. (by `microthread` module)
I write code that pause-able vm by STACKLESS features, keep last code_state in entry code_state, etc thing...

**Comment by pfalcon** [comment]
Being implemented by https://github.com/micropython/micropython/pull/2165

**Comment by pfalcon** [comment]
From https://github.com/micropython/micropython/issues/2233#issuecomment-231761923:

>> if you noticed, there were some random glitches with threading tests in travis.

> Ok, I see them. I just made a few changes to try and fix it, but I can't reproduce those particular errors in stress_heap and thread_lock4.

@dpgeorge : Yesterday I saw thread_lock4 fail on my local machine, which was particularly overbusy at the moment. So, it's all load-related (loadavg: 7.90). No more detail, I just re-run it and it disappeared.

**Comment by dpgeorge** [comment]
> Yesterday I saw thread_lock4 fail on my local machine, which was particularly overbusy at the moment.

It would be very interesting to know if you had pulled 2847d7431d9334220445e93dc7af707821e80d5e at that time?  That commit was made for an independent reason (getting thread tests to run efficiently on pyboard), but touches some of those tests that had issues, so they might work more reliably now (although that's actually a bad thing, because if there's a bug it needs to be fixed, not worked around).

**Comment by pfalcon** [comment]
Looks like no, I didn't have that commit.

**Comment by pfalcon** [comment]
Threading is now supported.

**Comment by andreybavt** [comment]
@pfalcon 

> Threading is now supported.

is it available on esp8266?
