### ISSUE TITLE
ESP32 - BT Scanning Broken ?

### ISSUE THREAD

**Issue by diginfo** [micropython/micropython#6315]
https://forum.micropython.org/viewtopic.php?f=18&t=8842

When I revert back to April build, BT scanning works, with current release nothing is detected.

**Comment by jimmo** [comment]
Looks like you're using unstable builds, but your code is still using the v1.12 API. The API has changed (this will be in the v1.13 release notes). In particular your issue is likely the IRQ event numbers have changed. The docs have been updated though, please see:
https://docs.micropython.org/en/latest/library/ubluetooth.html#ubluetooth.BLE.irq

**Comment by diginfo** [comment]
Thanks very much for helping, but changing:

` _IRQ_SCAN_RESULT   = const(1 << 4)`

to

`_IRQ_SCAN_RESULT   = const(6)`

Did not solve the issue and it's still unable to scan

**Comment by diginfo** [comment]
OOps - yes that solved it, thanks :-)
