### ISSUE TITLE
memory chip question

### ISSUE THREAD

**Issue by zxc199108** [micropython/micropython#6327]
GC: total: 92736, used: 79968, free: 12768
 No. of 1-blocks: 834, 2-blocks: 96, max blk sz: 384, max free sz: 266

the max free sz is 266*16=4256 bytes，but free is 12768 bytes. so when I setup thread(5KB), memory alloc failed.

How can i solve this problem?

**Comment by peterhinch** [comment]
You are suffering from RAM fragmentation. It's best to instantiate objects which require a large block of contiguous RAM soon after program start, before fragmentation occurs. That said, you are running very tight on RAM. Have you tried frozen bytecode to reduce RAM usage?

Incidentally queries like this are best raised in [the foum](http://forum.micropython.org/index.php) rather than in this bug tracker.

**Comment by stinos** [comment]
This is better suited to ask at the [forum](https://forum.micropython.org) (and IIRC it has been asked and anwered there already) as it's merely a question, not an issue report or bug.

**Comment by zxc199108** [comment]
OK ,Thanks
