### ISSUE TITLE
two dimensional list/array

### ISSUE THREAD

**Issue by GerfriedC** [micropython/micropython#6394]
While with standard python numpy might be used to create a matrix
 t_w=np.zeros((self.n_el,self.n_t+1))
in micropython I'm using
       t_w=[[0]*(self.n_t+1)] * self.n_el
Unfortunately assignement and retrieval of single elements is not working the same way. One dimension is lost in micropython.
t_w[i][j]=
Any ideas to solve are highly appreciated.
many thanks

**Comment by jimmo** [comment]
This is because when you use the multiply operator on a list, the elements are shallow copied.

Think of y=[x]*n as being y=[x,x,x,x], so modifying y[0][i] is the same as x[i]  (and will therefore be the same as y[1][i], etc).

i.e. each element of the outer list is actually the same inner list.

```
>>> x = [[0]*4]*4
>>> x
[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
>>> x[0][0] = 1
>>> x
[[1, 0, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0]]
>>> 
```

One way to solve this is with a list comprehension instead:

```
>>> x = [[0]*4 for i in range(4)]
>>> x[0][0] = 1
>>> x
[[1, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
```

If you're using numpy, you might also want to check out either of the efforts to bring numpy-like functionality to MicroPython:
https://github.com/v923z/micropython-ulab
https://github.com/nickovs/uumpy
