### ISSUE TITLE
Please consider DOC entry on compatible GCC compilers

### ISSUE THREAD

**Issue by Willi-Villaton** [micropython/micropython#6443]
Hey   guys, 

so im currently working with micropython on a PIC controller. Because of problems with C extensions i tried to compile the stand-alone Windows-Port("make" in cmd on micropython/ports/windows). After two days of trying to find the error i recognised that my colleague was running the same configs on an older and different version of gcc. So we researched this issue a bit and came to the conclusion that **MinGW does not compile it whilst Octave GNU does**. We tested this for Octave Gcc Version 7.4.0 and 9.2.0 and MinGW Gcc Version 8.2.0 and 9.2.0. Then we compared the latest compiler versions (9.2.0) and found that those two versions differ in size and compile style.
![image](https://user-images.githubusercontent.com/59259707/93064651-0e9e8680-f678-11ea-8cc7-b590167b2f0c.png)

But sadly we are in a bit of a rush with our project and dont have the time to do a full research. But it would be nice if you could implement some kind of list on the webpage or in the Docs in wich all suitable compilers are named. Thank you :)

Greetings!

**Comment by stinos** [comment]
> conclusion that MinGW does not compile it whilst Octave GNU does

That's not a very accurate description: what you call 'octave gcc', i.e. the gcc which is distributed with Octave, is actually still just 'mingw gcc' i.e. a build of gcc which runs on Windows. The file size of the compiler is not relevant here, however it would be very helpful if you could run `gcc --version` for both versions and post the output, and  Additionally it would be very interesting to know exactly which errors you encounter: we cannot really change the documentation without knowing what is wrong. Also note that the Appveyor and Travis builds can succesfully build the Windows port using a variety of gcc versions, both MSYS2 and cross compiler versions, so we don't mention version numbers explcitly.

**Comment by Willi-Villaton** [comment]
Hey, that was fast :D
What you requested (gcc --version) is what is was trying to point out with Octave Gcc and MinGW Gcc.
Used gcc versions (not MinGW or Octave Version) are [MinGW]: 8.2.0, 9.2.0 and [Octave]: 7.4.0, 9.2.0.
**MinGW Version recent(updated today to check with the recent gcc version) with GCC Version 9.2.0:** 
![image](https://user-images.githubusercontent.com/59259707/93070273-f54d0880-f67e-11ea-8144-82bf82d1ea7e.png)
![image](https://user-images.githubusercontent.com/59259707/93071115-fd597800-f67f-11ea-962d-b07809bf2dad.png)
**Octave  Version 5.2 with GCC Version 9.2.0:**
![image](https://user-images.githubusercontent.com/59259707/93070889-b8354600-f67f-11ea-8e2b-7cf88b623c23.png)
![image](https://user-images.githubusercontent.com/59259707/93071195-1bbf7380-f680-11ea-9278-823a3648bcf6.png)

User Variable Path in Example:
(I swap them to use the one needed)
![image](https://user-images.githubusercontent.com/59259707/93071370-5e814b80-f680-11ea-8c89-819aa31ba962.png)

For the second point:
This error comes up for every direct definition of "__USE_MINGW_ANSI_STDIO"
![image](https://user-images.githubusercontent.com/59259707/93071263-37c31500-f680-11ea-87a7-c63624fc4912.png)
We then tried to take out the -Werror flag inside the makefile to only treat them as a warning but there are more problems exept those while trying to build the QSTR.

**Comment by Willi-Villaton** [comment]
Addition:
I just reproduced the errors without -Werror in the ports/windows/Makefile for completion.

Firstly there are all warnings because of the direct definition of "__USE_MINGW_ANSI_STDIO"
As seen above

Secondly there are a whole bunch of other warnings which also address the declaration of use_mingw_ansi_stdio but with a pragma message:
![image](https://user-images.githubusercontent.com/59259707/93073539-5b3b8f00-f683-11ea-96af-2078c4d446f4.png)

And finally there is this error wich occures through the definition of EWOULDBLOCK / MP_EWOULDBLOCK. Somethings undefined here:
![image](https://user-images.githubusercontent.com/59259707/93073670-92aa3b80-f683-11ea-91ea-1cd0cc2fc621.png)
This also occures for every time EWOULDBLOCK is used/referenced.

**Comment by stinos** [comment]
Thanks for the information! I didn't check it in detail yet, but unless I'm mistaken the problem is that the mingw gcc version is 'mingw32' and not 'mingw-w64' (which is a more common fork of mingw32 and also the one which comes with Octave). Those names are super confusing, but the point is that MicroPython only supports mingw-w64 and not mingw32. This is briefly hinted in the Windows README.md file, though it could probably be made more clear. Moreover the information in the README is a bit out of date: though it specifically mentions 'you may need to disable -Werror' it still sounds as if it might work, but probably since it was written new features were added and it now doesn't compile anymore at all, as you figured.

Can you confirm that's the problem? Where does your mingw distribution come from?

**Comment by Willi-Villaton** [comment]
Hey, that actually seems to be the problem. 
My MinGW distribution is from the official site which is indeed the 32bit version. (https://osdn.net/projects/mingw/releases/)
I would recommend adding this information to the "Getting Started" on the Homepage. This would be really helpful for beginners to not get knocked over with weird error messages after only doing what is hinted in various getting started tutorials.
Thank you for the fast support and the solution :)

**Comment by stinos** [comment]
> I would recommend adding this information to the Docs on the Homepage. 

You mean on http://docs.micropython.org? Thing is that's mostly about MicroPython, the language, and has no build instructions (I think). The go-to place for build instrcutions is really the README.md for each port. However it would help if that was made much clearer in the main README.md instead of buried in a sentence halfway.

**Comment by Willi-Villaton** [comment]
> However it would help if that was made much clearer in the main README.md instead of buried in a sentence halfway
Yep thats right. In any case a clear hint would be great and save a lot of detective work in the unfortunate case of a wrong compiler.
And maybe it would be worth considering a "Getting Started" Page on http://docs.micropython.org to make things easier for beginners in micropython like myself. =)

**Comment by stinos** [comment]
Little update: there's been some discussion on this in Slack. Summary: everyone agrees that the build instructions should be easy to find from the main README; it serves as the landing page for the project so the instructions for 'how do I start this thing' should be at most 1 click away. It's not too hard to add such links, but because there's an ongoing Season of Docs project for MicroPython, and as part of that build instructions might be moved around so it doesn't make much sense of starting parallel work to get this sorted out, yet.

**Comment by stinos** [comment]
See #6469
