### ISSUE TITLE
[STM32WB] sleep or deepsleep wakeup on pin irq

### ISSUE THREAD

**Issue by dmazzella** [micropython/micropython#6674]
Hi, 
is there any way to wake up from sleep or even better deepsleep using the pyb.Switch pin (A10)? or other solution for this?

Regards,
D.

**Comment by peterhinch** [comment]
[This doc](https://github.com/peterhinch/micropython-micropower/blob/master/UPOWER.md) details how to wake from deepsleep. The hardware only permits certain pins to be used. As a general point, queries like this are best raised in [the forum](http://forum.micropython.org/index.php) rather than in the MicroPython bug tracker.
