### ISSUE TITLE
upip uninstall/remove package

### ISSUE THREAD

**Issue by mat-l** [micropython/micropython#6742]
Dear all,
I am new to MicroPython, therefore I am having probably an easy question, but I didn't find any answer yet.

How can I uninstall / remove / delete a package, which I have installed by means of upip?

Best regards

**Comment by peterhinch** [comment]
Support questions should be raised in [the forum](http://forum.micropython.org/index.php), not in the MicroPython bug tracker.

A package installed with **upip** (or otherwise) does not consume RAM or CPU time unless your application uses it: the package only occupies space in the filesystem, which is often plentiful. So there is often no particular need for removal. To recover the filesystem space you will need to find the directories and files and delete them. The means for doing this depends on the tool or IDE you are using.
