### ISSUE TITLE
Assertion error in re1.5

### ISSUE THREAD

**Issue by jepler** [micropython/micropython#7078]
Build the Unix port with DEBUG=1, then try to match a particular regular expression.

```
src/micropython/ports/unix$ ./micropython
MicroPython v1.14-122-g9fef1c0bd-dirty on 2021-03-27; linux version
Use Ctrl-D to exit, Ctrl-E for paste mode
>>> import ure as re
>>> re.match(63*"a" + "|", "x")
micropython: ../../extmod/re1.5/recursiveloop.c:79: recursiveloop: Assertion `!"recursiveloop"' failed.
Aborted
```

The original regular expression I encountered this with was a long series of "literal|literal|..." intended to be useful, the above is a minimized version.

I'm guessing it has to do with the offset of a `split` being large enough that it becomes negative .. with 62 repetitions of 'a', everything is 'okay'.

I think this has to do with overflowing some 8-bit offset.  When additionally defining MICROPY_PY_URE_DEBUG, the not-quite-crashing expression's disassembly can be seen to begin:
```
>>> re.compile(62*"a" + "|", re.DEBUG)
 0: rsplit 5 (3)
 2: any
 3: jmp 0 (-5)
 5: save 0
 7: split 135 (126)
 9: char a
```
while the crashing version has a negative `split` target at instruction 7:
```
>>> re.compile(63*"a" + "|", re.DEBUG)
 0: rsplit 5 (3)
 2: any
 3: jmp 0 (-5)
 5: save 0
 7: split -119 (-128)
 9: char a
```

Knowing all this, it looks like my regular expression is simply too much for re1.5. However, maybe the problem could be found at compile time and changed to result in an exception rather than an assertion error (or, probably, unpredictable behavior at runtime if assertions are disabled)

**Comment by dpgeorge** [comment]
Thanks for the report.  Yes it does look like an overflow of the jump offset for rsplit/split.  It's currently an 8-bit signed offset so has a limit of about +/- 127.

It might be possible to improve re so that it can support larger offsets.  Eg add a new instruction `OFFSET_HIGH_BYTE` (with a byte argument) which prefixes any instruction that needs additional range.  Otherwise, yes, probably a good idea to raise an exception if this situation is encountered.
