### ISSUE TITLE
[ESP32]- SIM800 / SIM7600 gprs support at current 1.14 uPy

### ISSUE THREAD

**Issue by kindmartin** [micropython/micropython#7083]
Hi all, not sure if a issue, it was an issue before as after reading those [3740 ](https://github.com/micropython/micropython/issues/3740) and related old posts, I'm still looking to make easy /readable code to connect gprs internet data an ESP32 + SIM800 (I'm using now a ttgo ttcall and also a PCIe with sim7400 LTE).

I really miss the simplicity of old loboris worked with this, but I want to stay here in the present, with 1.14. any guide on how to declare apn and related AT commands and enable a new gprs IP interface via serial to that esp32?
thanks in advance. I'm struggling with sim7600 at manual... not case I cannot make it work to use sockets or http request with urequests, etc.

M

**Comment by jonnor** [comment]
There are multiple discussion threads about this in the forum, including https://github.com/orgs/micropython/discussions/11649
Since it is not in scope for the MicroPython core repo to have SIMxxx module support, I propose the discussion continues here.
I also found https://github.com/basanovase/sim800 for SIM800
