### ISSUE TITLE
utime: Syntax error <function> not reported.

### ISSUE THREAD

**Issue by chrismas9** [micropython/micropython#7126]
if `ticks_ms` instead of `ticks_ms()` is used inside `ticks_add` or `ticks_diff`
`<function>` syntax error is not reported.

![image](https://user-images.githubusercontent.com/6243558/115108527-4e35a400-9fb4-11eb-9d77-95529f3b7a39.png)

**Comment by dpgeorge** [comment]
This is essentially the same as #7115.

It's definitely not a syntax error because there is nothing illegal about the syntax.  It could be a type error because ticks add/diff only accepts small integers and above it is passed a function.  But (see #7115) the idea with these ticks functions is that they are efficient so no checks are done (and it's still safe, cannot crash).

**Comment by chrismas9** [comment]
Thanks

**Comment by tongdee9070** [comment]
The info is goo but too over welming, thank you
