### ISSUE TITLE
esp32: Station interface doesn't activate mDNS responder

### ISSUE THREAD

**Issue by rubydesign** [micropython/micropython#7169]
So i have been trying to get one esp32 to connect to another, without actually hardcoding the ip of the "server".
I am a micropython newbie, but an older programmer, so i think the fact that this has taken me 2 days is a lot to do with documentation and the intricacies of MP and detailed knowledge of dns that mp should not assume a casual user has. 

I would propose to add some lines to the esp32 network section, ie https://docs.micropython.org/en/latest/esp32/quickref.html
Maybe a line about how to set the hostname. (also when, if there are restrictions, ie before or after?)
The fact that one needs a station and it does not work with an ap
And that the station needs to be connected to a router.
Maybe a mention about the .local and how to ping from a pc.
And code to use the hostname from a second esp, ie in getaddrinfo.

I would be happy to make a pr for the esp docs if no one of the coders want to do this.

**Comment by karfas** [comment]
This issue sounds very confusing to me.

Please take a deep breath and try to describe what your problem exactly is.

First, there is no **generic** way to "set the hostname" in a way so this machine can be found by others. However, you can add the IP address to all /etc/hosts files in reach and/or provide a name in your DHCP/DNS server (most likely part of your WLAN router).

Why do you need a station and what is "it" not working with an AP ? The AP of an ESP32 works fine (but does NOT include a DNS server out of the box).
Yes, a WLAN client (station) needs an access point to connect to. Nothing new. Everybody with a smartphone/tablet/whatever knows this.
What is ".local" ? Nobody needs this to ping an IP address.
And, getaddrinfo() works quite well with hostnames (provided correctly configured DHCP+DNS servers exist in your network).

Go ahead with a documentation patch, but describing half of the internet's infrastructure in two sentences will most likely be more confusing than the current situation.

I'm sorry if this sounds harsh. But I think someone who buys an ESP32 (yes, because it has WIFI) and tries micropython will either be comfortable to use two or three IPv4 addresses or will have the knowledge to configure a router/dns server.

**Comment by rubydesign** [comment]
Ok @karfas , have taken a breath and am calm. Let's start from the bottom: the assumption about anyone with an esp knowing much about the internet. They cost 5e, are available to anybody. Any micropython (and python) is heavily maeketed for schools by raspberry (especially since the pico). So no, an understanding of inner working of dns, or knowledge of dhcp should not be assumed.
Then ".local" is defined in ports/esp32/modsocket.c as MDNS_LOCAL_SUFFIX , and only if present is it chopped off and a call to mdns_query_a issued. I thought this would be worth mentioning.

The "it" was the fact that the hostname resolution depends on the fact that the esp is connected to a router (via the station off course). 

Maybe to clarify my confusing statements: I have esp "S" and esp "A" .
I use a station interface on S and an AP on A.
I want to have a server on A, ie am listening to 0.0.0.0.
I want S to connect (socket) to the server on A, so i need to call getaddrinfo with an ip or name.
I want to call getaddrinfo with a name (not hardcode the ip)

This works **if, and only if,** A is itself using a station interface to connect to a router.

For me this was not obvious, because of the lack of documentation i feel.
But if you feel that i am not knowledgeable enough, ok. I am quite wary of writing PR's that will not get accepted though, so at the moment that won't happen.

**Comment by karfas** [comment]
Thank you very much.
I think I understand th problem now.
Most likely we will disagree about the DNS knowledge thing. 
I was also not aware of someone stripping .local from DNS Queries (sounds like a Bug for me, if this behaviour isn't defined in a RFC).

BTW, I have next to no influence at all to PRs, Documentation, Micropython marketing. I'm just an interested (and very often annoyed by missing documentation and features) uPy user who learned python during the last months.

Regards, 
Thomas

**Comment by karfas** [comment]
Maybe also interesting: a quick Google search for "Micropython DNS" found a few DNS Server implementations for ESP[32,8266]. Most likely many of them will need care and feeding to use them in own projects (as usual).

**Comment by karfas** [comment]
> Maybe to clarify my confusing statements: I have esp "S" and esp "A" .
> I use a station interface on S and an AP on A.
> I want to have a server on A, ie am listening to 0.0.0.0.
> I want S to connect (socket) to the server on A, so i need to call getaddrinfo with an ip or name.
> I want to call getaddrinfo with a name (not hardcode the ip)
> 
> This works **if, and only if,** A is itself using a station interface to connect to a router.

I'm sorry, it looks like I had not read this good enough.

If you want to connect something on B to a server  on A, B needs only the credentials to connect to A's access point.
When B is connected, it got an IP address by DHCP together with default routing address pointing to A (provided by the DHCP server coming together with using A's access point features).
B can query the routing address using wlan.ifconfig and can use this address to connect to A (e.g. using getaddrinfo).
No hard coded address at all, but you will (of course) have hard coded Wifi credentials somewhere on B.

**Comment by rubydesign** [comment]
Ok, that ifconfig is good to know. Almost in itself a documentation issue, how us one to know these things if they are not written.
To be honest though i am moving off micopyton, partially because these kind of things. The main one of these is the bad support for working with libraries (not even making that an issue, though it clearly is). I will probably close this soon, as noone from the team has picked it up / cared.

**Comment by jimmo** [comment]
@rubydesign I agree this is definitely a confusing area, and it comes up in the forums too.

> This works if, and only if, A is itself using a station interface to connect to a router.

I think potentially what's really confusing here is that DNS and mDNS are not at all the same thing (even though on ESP32 we sort of confuse the two by setting them both with the `dhcp_hostname` config option).

In your scenario, DNS doesn't apply because, there is no DNS server  (as @karfas has pointed out, although the ESP32 AP provides a DHCP server, it does not do DNS).

But they are able to resolve eachother via mDNS. However, the mDNS responder is only configured when the station gets an IP address (which explains what you're seeing where you also connect the AP to your router). The bug here is that there's no code path that activates the mDNS responder for the station interface. (But you're right, the docs need to be improved to explain exactly what the `dhcp_hostname` option does).

> Ok, that ifconfig is good to know. Almost in itself a documentation issue, how us one to know these things if they are not written.

Yeah I would have suggested finding out the gateway address as the best approach anyway for this scenario of "connecting to your access point" (instead of DNS or mDNS). Perhaps for this reason it's not worth the extra code to make the AP activate the mDNS responder?

I'll be the first to agree that the documentation needs work, but in this case:
https://docs.micropython.org/en/latest/library/network.html#network.AbstractNIC.ifconfig

(And of course it's not obvious that you want the AbstractNIC docs either... this could be improved)

**Comment by rubydesign** [comment]
@jimmo Thanks for responding. And very sensibly too.
While i do understand you changing the title, i really think this is a docs issue. I am ok with the functionality being what it is, even quirky, if i just know (easily).

I have moved on from this issue and was about to close this issue, I don't like to be the reason for long hanging issues that no one (on the team) cares about. Seeing as you are on the team, please state clearly if you don't want me to close this (even i personally have no interest in it any-more)

From a larger perspective i can say that i was super excited when the pico came out and python was on it. As an older model and long time coder i have difficulties dealing with the tediousness of compiled languages.

And yet, i have dropped micropython and am developing on platformio. The reason for this is 2 fold:
- this kind of docs issues. First contact with MP is good, but then in the details it is unclear. One (as a newbie) gets the feeling that there is a lot of old school geeking in the  project (culture), RTFC kind of thing. Where true men read the code to find things out and making things easy for newbies is for someone else (some else than the developer writing new hot mp code)
- library management is NOT up to prime time. We are living in the 2k 20ies and every decent language has a library manager. Like pip for python. But the upip is not doing its job. Once i had a library or two, space on the device ran out. And i had to find out that the upip does not compile the code, and if i would have wanted to i would have had to get that working myself. Pip, platformio, bundle all do the compilation for the user, just require a little config file stating the dependencies. This is how it should be and needs to be for mp to become more widespread use. 
 
On Platform i just add the dependency, done. Press the compile and upload, go. I feel the whole model for development with mp is not quite thought through. A repl is off course great for debugging and a quick start. But editing files on the device does not play well with source code control. And being able to edit either on the device or on the machine is confusing (without git, how do i know what i changed). So yeah, back to c++, haven't done that in 25 years.

So that was the long version of why even an enthusiastic newbie stopped using mp. I am sorry i have no time to help with theses issues, but am available for more discussion. As i said, i would close this issue now if you don't object.

Thanks for answering and i hope you can take this in the constructive way it is meant.
(I have written a compiler, i understand very well the achievement that has been made here)

**Comment by jimmo** [comment]
> @jimmo Thanks for responding. And very sensibly too.
> While i do understand you changing the title, i really think this is a docs issue. I am ok with the functionality being what it is, even quirky, if i just know (easily).

Thanks, yeah I should have been clearer -- I agree this is probably best addressed by docs. i.e. "clarify that the...  Station interface doesn't activate mDNS responder" rather than "fix the fact that the ...  Station interface doesn't activate mDNS responder".

You're welcome to close it, but I'm keen to keep this open as a reminder to update the docs.

> Thanks for answering and i hope you can take this in the constructive way it is meant.

Yes, absolutely. Thanks for the feedback and agree that this is feedback we hear from multiple sources and is definitely something that we'd like to address (and the library management is a personal interest of mine). MicroPython is a small team though and there's a lot to do!

**Comment by rubydesign** [comment]
> Yes, absolutely. Thanks for the feedback and agree that this is feedback we hear from multiple sources and is definitely something that we'd like to address (and the library management is a personal interest of mine). MicroPython is a small team though and there's a lot to do!

Well i'm glad to hear that. And i would help, only i just bought this!
Still when you get to the library i might
