### ISSUE TITLE
Support constant values of aggregate types

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#722]
Currently, unlike CPython, uPy doesn't support constant tuples, dicts, etc. Any such object is constructed at runtime, which takes time, (lot of) VM stack, etc.

It also precludes efficient usage of almost-core features, like in-place OrderedDict's.

**Comment by dpgeorge** [comment]
I've had a patch for some time now for making a const table of pointers per function and having the bytecode index that table.  But...

> Exactly, inline pointers will waste 2 bytes on average.

No, surprisingly they don't.  They waste 0 bytes in almost all cases due to a very fortuitous layout of the bytecodes that mean that the ptr argument to the bytecode op is always aligned.  The main use of pointers in bytecode is the MAKE_FUNCTION opcode, which is almost always followed by a STORE_NAME:
```
MAKE_FUNCTION <ptr> -- 1 + 4 bytes
STORE_NAME <qstr> -- 1 + 2 bytes
```
As you can see, combined they make exactly 8 bytes, so a long sequence of these pair of ops will always have the ptr aligned if the first one is aligned (valid for a 32 bit machine).  And a long sequence of these ops is generally what you get when defining functions/methods.

So, with this patch both code size and RAM usage increase noticeably.  I've not been able to think of a way to reduce it.

**Comment by dpgeorge** [comment]
Commit f2040bfc7ee033e48acef9f289790f3b4e6b74e5 implemented a global constant table per .mpy file.

Commit 35c0cff92bea230f8e16a8a7cdd50ea5f6a9df03 added support for constant tuples (where all elements are constant literals).
