### ISSUE TITLE
AttributeError: 'function' object has no attribute '__module__'

### ISSUE THREAD

**Issue by schef** [micropython/micropython#7259]
Hi guys,
is it possible to get the module name out of the function?

**Comment by dpgeorge** [comment]
Short answer is no, it's not possible because MicroPython does not store any reference from a function object to the module it was defined in.  This is because MicroPython tries to use as little RAM as possible and having a reference takes up RAM.

Long answer: you can in some cases get to the module via `function.__globals__['__name__']` and then index this into `sys.modules`.

**Comment by schef** [comment]
Thanks.
The recommended method works! :)

**Comment by schef** [comment]
Thanks. The recommended method works! :)
