### ISSUE TITLE
RFC: change WLAN keywords authmode->security, password->key

### ISSUE THREAD

**Issue by dpgeorge** [micropython/micropython#8083]
As proposed by @iabdalkader in https://github.com/micropython/micropython/pull/8022#issuecomment-979232486:

> I think auth, authmode and password should all be deprecated in favor of security and key, as referred to in the 802.11 IEEE standards, but also logically authentication is only a part of the security protocol.

Eg `wlan.config(password="abc")` would become `wlan.config(key="abc")`, among others.

The change would be made in a backwards compatible way, such that the existing keys would be supported as well.

Please comment if you think this is a good or bad idea.

**Comment by dpgeorge** [comment]
Also could consider renaming `essid` to `ssid`, since the latter seems more widely used.

**Comment by dpgeorge** [comment]
I think this is a good change to make, so let's move forward with this.

**Comment by iabdalkader** [comment]
On my todo list.

**Comment by iabdalkader** [comment]
I checked the WLAN keyword args across ports and in the docs, and it seems no port/module shares the same args names with another (except for esp ports):

network_cyw43: `essid`, `auth`, `password`
network_ninaw10: `essid`, `security`, `key`
esp based ports: `essid`,  `authmode`, `password`
modncc3k.c: `ssid`, `security`, `key`
cc3200 port: `ssid, and an `auth` tuple
wipy: `ssid` and an `auth` tuple.

I suggest a breaking change from `essid` -> `ssid`  since it's usually a "required" arg and usually passed as a positional arg from scripts, and for the `auth` and `password` these can be changed in a backwards compatible way.

**Comment by dpgeorge** [comment]
> I suggest a breaking change from `essid` -> `ssid` since it's usually a "required" arg and usually passed as a positional arg from scripts

Yes that makes sense.

But note that `essid` is also used in `.config(essid=...)`, and that can be changed in a backwards compatible way.

**Comment by iabdalkader** [comment]
> But note that `essid` is also used in `.config(essid=...)`, and that can be changed in a backwards compatible way

Yes that's easy to fix.

**Comment by iabdalkader** [comment]
https://github.com/micropython/micropython/pull/8725

**Comment by dpgeorge** [comment]
Done, see 6e868d47dc5dd7a90444f1173118b7d57e1e4df7
