### ISSUE TITLE
V1.18 breaks microservo (MG90S) functionality through PWM on ESP32. Works on Pico though.

### ISSUE THREAD

**Issue by AllanMisasa** [micropython/micropython#8377]
My students and I have experienced this on the generic ESP32-WROOM 38 pin.

**Comment by robert-hh** [comment]
Thank you for the reporting. This issue was reported already at #8189, #8306 and #8345. #8189 is fixed in the actual nightly builds. For #8306 and #8345 exists a PR. #8306 can be avoided by first configuring a different Pin for PWM and then the Pin used for the servo. #8345 happens only if more than one channel is used at the same frequency, and the frequency of one channel is changed from and back into that common frequency.
Errors like these should not happen, but at least, your students had an exercise in failure tracing, which is definitely an important part of learning to code.

**Comment by dpgeorge** [comment]
Most recent fix for this was in 55a0125a154a9c13363d900e0caccd218bce0a54.  I think this issue can be closed.  Please reopen if it's still not working.
