### ISSUE TITLE
mpremote commands select incorrect device

### ISSUE THREAD

**Issue by abumalick** [micropython/micropython#8736]
I have difficulties to use mpremote, I use the connect command with the correct device, after that I would expect other commands to use the same device (or allow me to specify the device)

```bash
~/clock-py | master ?6 ▓▒░ mpremote connect /dev/cu.usbserial-0001                        ░▒▓ ✔ | 13s 
Connected to MicroPython at /dev/cu.usbserial-0001
Use Ctrl-] to exit this shell
div:2
load:[cd]fff0030,len:4540
ho 0 tail 12 room 4
load:0x40078000,len:12344
ho 0 tail 12 room 4
load:0x40080400,len:4124
entry 0x40080680
MicroPython v1.18 on 2022-01-17; ESP32 module with ESP32
Type "help()" for more information.
>>> %                                                                                                               
~/clock-py | master ?6 ▓▒░ mpremote repl                                              ░▒▓ ✔ | 4s 
Connected to MicroPython at /dev/cu.Bluetooth-Incoming-Port
Use Ctrl-] to exit this shell
~/clock-py | master ?6 ▓▒░ mpremote disconnect                                        ░▒▓ ✔ | 4s 
Connected to MicroPython at /dev/cu.Bluetooth-Incoming-Port
Use Ctrl-] to exit this shell
````

Why the `disconnect` command enters the shell?

fs commands hangs, without any result:
```
~/clock-py | master ?6 ▓▒░ mpremote fs cp boot.py :                                   ░▒▓ INT х | 11s 
```

* Please provide as much information as possible about the version of MicroPython you're running, such as:
 -  firmware file name: esp32-20220117-v1.18.bin
 - git commit hash: (how can I get this?) 
 - port/board: /dev/cu.usbserial-0001 ESP32
 - version information shown in the REPL: MicroPython v1.18 on 2022-01-17; ESP32 module with ESP32

**Comment by jimmo** [comment]
>  I use the connect command with the correct device, after that I would expect other commands to use the same device (or allow me to specify the device)

@abumalick  The idea with mpremote is that commands can be chained *in the same invocation of mpremote*, allowing you do several operations in the same "session" (this is important because a new session will typically soft-reset the device). There's no global state between invocations.

i.e. `mpremote connect /dev/cu.usbserial-0001 fs cp boot.py : repl`

In your case your subsequent `repl` and `disconnect` are using the default port.

FWIW, it would be helpful to make mpremote smarter at detecting the "right" serial port to use. e.g. on Linux `/dev/ttyACM0` or on macOS `/dev/cu.usbserial*`. Defaulting to the Bluetooth device isn't very useful.

**Comment by jimmo** [comment]
> I believe we should make it clear in the documentation:

Yes, the docs don't really spell this out and it would be good to improve them.

> I tried the command that you gave me and get an error message:

@abumalick  You're right sorry, `fs cp` was a bad command to use as an example because it assumes the rest of the arguments are files. (We should add some sort of terminator to the file list to make this example work).

There are two examples in the docs that show this better:

```
mpremote eval 1/2 eval 3/4
mpremote mount . exec "import local_script"
```

**Comment by mattytrentini** [comment]
If it's clear @abumalick, please close this ticket :)

**Comment by abumalick** [comment]
yes, chaining commands allowed me to inject files and it kind of allowed me to have a better workflow.

I believe however than mpremote would allow better development workflows, like syncing a directory and soft reset the device after the synchronization is done. I would like to understand how developers are working on microcontrollers with micropython with multiple files and librairies.

But yes this issue is not an issue, it is misunderstanding from my part and maybe a lack of clarity in the documentation.

Thanks a lot for your feedback @jimmo
