### ISSUE TITLE
Need help to complete PR #8872

### ISSUE THREAD

**Issue by ska-la** [micropython/micropython#8875]
Please, anybody, help. I have no patient to fix commits formatting. It's a third attempt. I've got advice of Damien George to do:
git push --force
but I don't understand how and where it must be done.

**Comment by dlech** [comment]
Change `upstream` to `origin`.

**Comment by jimmo** [comment]
> git push --force upstream master

As @dlech said, upstream isn't your fork. What's the name of your remote (likely "origin")

But also you don't want to push to the "master" branch. It likely should be "nucleo_h755zi".

You've already pushed this branch though to create the PR, so if it already has its upstream set, then just "git push -f" should work. Otherwise set its upstream first with "git branch -u origin nucleo_h755zi", then "git push -f".

Note.two distinct meanings of "upstream"... both the name of the remote, and also a branch may have an upstream configured.

**Comment by ska-la** [comment]
Thanks, folks. for all tips.
