### ISSUE TITLE
Run on core 0 on esp32

### ISSUE THREAD

**Issue by MATTYGILO** [micropython/micropython#8971]
I would like to be able to specify that I want to run the creat_new_thread on core 0 on an esp32

**Comment by jimmo** [comment]
Dual-core support is a frequently requested feature. It is not supported, which is why we pin to a single core (and the selection of which core has some history).

Please see https://github.com/micropython/micropython/issues/8927 and the referenced issues.

> I get this error: ../py/mpthread.h:38:10: fatal error: mpthreadport.h: No such file or directory 38 | #include <mpthreadport.h>

There's not enough information here to be able to help.
