### ISSUE TITLE
Ideas for a micro database

### ISSUE THREAD

**Issue by dpgeorge** [micropython/micropython#918]
Databases are useful for many purposes, eg for a webserver backend.  I would like to see some kind of database supported in uPy.  Criteria for the actual low-level DB implementation (the high-level Python module comes later):
1. Needs to run in minimal RAM, and not be huge in ROM.  Must be able to run on the pyboard.
2. We cannot use the server/client model since on pyboard we don't have processes.  It must be a C API.
3. We should not reinvent our own DB syntax/style.  Instead we should use a well known existing DB syntax.  We can implement a cut-down version if needed.
4. The DB should be stored as a file, and we should use (or be compatible with) an existing file format, so that the same DB file can be read on a PC using standard tools.

The obvious solution is sqlite3, since it satisfies points 2, 3 and 4.  The question is: can sqlite3 be shrunk down to fit in RAM and ROM?

**Comment by pfalcon** [comment]
Soooooo, databases... Perhaps I should start with why looking at it now. So, drama with dynamic linking support on arbitrary systems made me think that sqlite is actually a bloat. That's because static MIPS with axtls I made was almost 500K. Add sqlite, it will be almost a megabyte. Not completive with Lua at all.

So, I decided to look around at embedded DB engines, even if not SQL, but key-value or other nosql paraphernalia. What I found that even such simple things are the code size of sqlite or more. That applies to LevelDB, Sophia, Tokyo/Kyoto Cabinets, Metakit, Unqlite, etc. A little fresh air is LDBM already mentioned above (as alternative backend for sqlite). Presentation materials for its initial versions talk about "30K of object code", current version builds to 60K with -m32 -Os, progress. Then I suddenly heard about Sqlite4, project covertly running since 2011. It has more modular and layered architecture, with separate storage component (key-value DB), called LSM (And that's of course full turn of spiral - sqlite is back to using explicitly separate key-value store, like sqlite1 did). That would be the same 60K.

Then I spotted something like real gem - https://github.com/graemedouglas/LittleD . SQL database designed to run on higher Arduinos. Academic project, 10 commits over 2 years. No real docs or examples. Digging into code, I immediately spotted lack of indexes support. I made some laughs, but the guy responded that who cares, it can execute queries in 1K, and of course, plans for (distant) future are bright. For sorting, it for each row in queryset scans entire queryset to find next immediate row after it. O(n^2). The paper for this work isn't freely available, but even reading 1st page https://www.deepdyve.com/lp/association-for-computing-machinery/littled-a-sql-database-for-sensor-nodes-and-embedded-applications-bc0bhTLY50 gave enough insight. All this madness didn't start 2 years ago. There's whole weird science on how to execute DB queries without memory http://www-smis.inria.fr/PUBFILES/2000/2000%20-%20PicoDBMS%20Scaling%20down%20Database%20Techniques%20for%20the%20Smartcard%20%28Best%20Paper%20Award%29.pdf . Who cares if it's O(n^m) - it's possible! (Impression from just turning pages, maybe they actually advocate use of indexes.) Or did you know that Adam Dunkels didn't skip hacking on this too? Contiki has Antelope embedded database (not SQL, but some simplified QL).

Well, back from bizarreness to real stuff. Just key-value store isn't interesting - it's just an on-disk dictionary and limited in used. To do data processing, it should be ordered keys-values. That's of course what LDBM and LSM are, but given that they're still too bloated, search should continue. LittleD's author pointed to https://github.com/iondbproject/iondb which implements few unbloated k-v storage algorithms, destined to be used as LittleD backend one sweet day. Except that it assumes that length of keys and values is fixed per table. So, toyness is deeply ingrained there (current LittleD also supports only fixed-size fields).

Finding a suitable codebase for ordered k-v store proved to be not easy - any maintained implementation gets bloated with features over time if not turned into complete DBMS, then there're developedness, licensing constraints. Here prior art helps again. BSD-licensed versions of BerkelyDB were already very well tried on millions of systems, and contain pretty clean B-tree implementation, compiling to ~15K of -m32 -Os code, with 1K for page cache (an unneeded luxury for mini-heap devices without moving storage parts).

So, I consider that the most viable option. Besides exploring Contiki Antelope of course ;-).

**Comment by pfalcon** [comment]
Should have mentioned that I reviewed Antelope (well, reads its paper). It's indeed tiny gem (indexes, joins, etc. supported). But: it's records are fixed-size (just like LiitleD/IonDB has). Also, it's optimized for append behavior. Perhaps I should re-read that part in paper 5 times more, but it essentially says that when deleting a record, it rewrites and entire database file to a new file.

There's also few pure-python databases, starting with Gadfly (SQL, was around since (or at) Python 1.1 or something), and some new things:

* https://github.com/msiemens/tinydb
* http://buzhug.sourceforge.net/
* http://labs.codernity.com/codernitydb/

None of these looks particularly adequate though, so I guess the best idea is to use Berkeley DB.

**Comment by pfalcon** [comment]
Initial implementation of "btree" module based on Berkeley DB 1.85 is landed in https://github.com/micropython/micropython/commit/8072162170851bae0e3d9a9e3ec6c7be64ad1253 and following commits. I've opened https://github.com/micropython/micropython/issues/2188 for specific discussion of that module.

**Comment by pfalcon** [comment]
`btree` in the codebase for more than year now, and now even starts to be leveraged. While this ticket contains wealth of ideas and information, I guess it's time to close it.
