### ISSUE TITLE
Consistent errno values

### ISSUE THREAD

**Issue by dpgeorge** [micropython/micropython#976]
On my linux box, native compilation has ETIMEDOUT with a value 110.  But cross compiling using arm-none-eabi gives ETIMETOUT a value of 116.  What to do here?  Which value to use?

**Comment by pfalcon** [comment]
I hit this today with https://github.com/micropython/micropython/issues/1533 . It gave error 116, and I had to go to compiler includes to find that it's ETIMEDOUT.

**Comment by dpgeorge** [comment]
Yeah, it's super annoying.

I want to provide a built-in errno module for stmhal.  Either as frozen module, persistent-bytecode or implemented in C, it doesn't matter, as long as "import errno" works on pyboard out-of-the-box without needing anything in the filesystem.

But, regardless of having built-in errno, we still need to decide whether to use port-specific errno values, or go for a fixed one.

**Comment by pfalcon** [comment]
> Yeah, it's super annoying.

Well, I forgot to add to my previous comment that I still find it *mildly* annoying ;-). Otherwise, just was doing bug triaging and found what to add to this old issue.

 I don't think it's big priority, but I'd give +0.5 for having a MICROPY_* config value, which, being defined, causes py/mpconfig.h to define typical error constants to standard values (either taken from Linux, or in the range beyond usual used by OS errors, to let differentiate them if they ever may be mixed in one port).

**Comment by danicampora** [comment]
+1 for builtin errno, and I vote for fixed values.

**Comment by dpgeorge** [comment]
If we're going to have a builtin module then it would need to be named "uerrno" with weak link called "errno".

**Comment by danicampora** [comment]
Yes, good point.

**Comment by dpgeorge** [comment]
uPy now provides its own errno's in py/mperrno.h.  From now on all errno symbols in code should use the MP_Exxx version.  A uerrno module is also provided, disabled by default.
